version: '3'
services:
  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
    volumes:
      - ./data/minio/data:/export
      - ./data/minio/config:/root/.minio
    environment:
      MINIO_ACCESS_KEY: minioaccess
      MINIO_SECRET_KEY: miniosecret
    command: server /export
    restart: always
